spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/rosie?serverTimezone=UTC
    username: root
    password: 123456
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
    # contexts: dev, faker

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  configuration-properties:
#    offsetAsPageNum: true
#    rowBoundsWithCount: true
#    reasonable: true
#debug: true

